sudo: required
services:
  - docker
  
before_install:
   - docker build -t iammanoj94/multi-docker -f ./client/Dockerfile.dev ./client
   
script:
  - docker run -e CI=true iammanoj94/multi-docker npm test
after_success:
  - docker build -t iammanoj94/multi-client ./client
  - docker build -t iammanoj94/multi-nginx ./nginx
  - docker build -t iammanoj94/multi-server ./server
  - docker build -t iammanoj94/multi-worker ./worker
  
# Docker CLI login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
# Take these images and push them to docker hub
  - docker push iammanoj94/multi-client
  - docker push iammanoj94/multi-nginx
  - docker push iammanoj94/multi-server
  - docker push iammanoj94/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-388755081422'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_KEY
  
  